### ISSUE TITLE
Order of iSoQ projects by creation date

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#46]
Hiya! I noticed that when I create a  new iSoQ project it doesn't automatically get listed last in the My Workspace section. I find this a bit confusing. I thinkt he projects should be listed in "My Workspace" by date of creation or addition (in the case they were shared) and that this order should remain stable. Perhaps newest projects at the top, and oldest projects at the bottom?

**Comment by MJWainwright** [comment]
Hi Damian, I don't think this one is closed. When I create a new project it still seems to be appear randomly in the list. We never noticed this issue before since I always only had 1 or 2 projects, but now I have 10+ and I can see it is really annoying. You create a new project and you expect it to appear on top but it doesn't. Can we make it so that the newest projects are at the top and the oldest projects are at the bottom. By newest and oldest, I mean based on date they were created (not edited).

**Comment by damian-garrido** [comment]
mmm, understand,
the way that i implement this is publishing the most recent worked at the top, because, if you need to work with an old document, you will need to scroll until you find it every time, but, if this have some modification, this will appear inmediatly at the top.
but, ok, for this i need to create a field that store this information, so probably, the old files will never sort in a correct way, so you need to delete all of them, at least at the test server, and then testing this enhancement.

**Comment by MJWainwright** [comment]
Ok, I will delete all the old ones. I think the way it is does not work. When I create a new project it just appears somewhere half way down the list of projects. I think users get used to where projects are in a list and if that jumps around it becomes frustrating. So newly created or newly shared projects at the top and older projects at the bottom. We can gather feedback about this during v.1

**Comment by damian-garrido** [comment]
@MJWainwright i made an update with this feature, can you check?

**Comment by MJWainwright** [comment]
It looks correct! Can you share a project with me so I can see what happens to a project that has been shared? Thanks!

**Comment by MJWainwright** [comment]
Looks good! Thanks
