### ISSUE TITLE
Page is jumping when user selects another page to display in the Tables

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#51]
Please check this display issue as it is really annoying! When the user is in My Data looking at the Step 3 or Step 4 table and clicks to advance to the next page of the table, sometimes the view is stable but sometimes it jumps the user down to the bottom of the page and then the user has to scroll up to find where they were. It does this sometimes when going from page 1 to 2 of the table, or sometimes 4 to 5. Yesterday Claire was getting confused thinking that her charac of studies table had suddenly become her meth assessments table but in actual fact it was that selecting another page to display bumped her down the page.

**Comment by damian-garrido** [comment]
this issue its a little bit complicated of fix.
the problem happens when you have, for example, 12 items in the first table, and 13 on the second one.
by default, tables show 10 items per page, so, if you change the page on the first table te numbers of the items change to the remaining elements, in this case 2, so, the layout change, making the page small, so this show the second table.

one solution, for the moment, its show the whole content on the table, so you never need to change of page between the tables, but if you have a lot of items, this page will be very large.

what do you think @MJWainwright ?

**Comment by MJWainwright** [comment]
Thanks for explaining Damian! Since it is not simple, let's leave it like it is and gather more user feedback. Maybe we can find a better solution for v.2!
