### ISSUE TITLE
Crazy characters appearing instead of accents on import

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#95]
![image](https://user-images.githubusercontent.com/72507850/110390357-c75ce580-805d-11eb-9073-53cbb9c1f11b.png)

Will send you the excel I was importing. It was prepared outside of iSoQ then imported but as youcansee the accents didn't hold

**Comment by damian-garrido** [comment]
this issue happen when u use a non international encoding (utf-8)
when you load your csv, this make a preview with the content, like the following image
![image](https://user-images.githubusercontent.com/25389333/110647369-874d4e00-8196-11eb-81b6-8c4d3b1605b9.png)
as you can see, the special chars are loaded well, because this file was saved as unicode utf-8

but, if i upload with a non international charset, using iso-8859-2, excluding japanese, greek, hebrew, arabic and other actors
![image](https://user-images.githubusercontent.com/25389333/110647887-03e02c80-8197-11eb-9616-f00e00244c1e.png)
this will display this kind of char �

the ISO-8859-2 its only for certain users around the world, if you send your file, for example a chinnese people, they will have the same issue with the content unless you change the encoding.

**Comment by MJWainwright** [comment]
But does it depend what default settings one has on their excel? If I download and see the funny characters and try to save as utf-8, it doesn't fix the problem. So what do you advise? We have to advise the users on what they can do to avoid this as it is a recurring problem.

**Comment by MJWainwright** [comment]
Hi Damian, I think I have figured this one out and we can close. I could provoke this issue by saving in a format other than utf-8. I could copy and paste from a non-utf-8 file to a utf-8 file and import without problems. If the table in iSoQ has funny characters appearing (because the import was not in utf-8) and then I export the table to XLS file, then the funny characters come with it and even if I save to utf-8, they cannot be fixed. So I think, like you say we just have to keep reminding people that they must save in the utf-8 format. Thanks!

**Comment by MJWainwright** [comment]
We can close this one.
